build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true
checks:
    php: true
coding_style:
    php: {  }
filter: {  }
tools:
    # Similar Code Detector
    php_sim: true
    php_cpd: false

    # Metrics
    php_pdepend: true

    # Some Metrics + Bug Detection/Auto-Fixes
    php_analyzer: true
