build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true
checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
coding_style:
    php: {  }
filter:
    excluded_paths: [Examples/*]
tools:
    # Similar Code Detector
    php_sim: true
    php_cpd: false

    # Metrics
    php_pdepend: true

    # Some Metrics + Bug Detection/Auto-Fixes
    php_analyzer: true
    php_code_coverage: false    
    php_loc:
        enabled: true
        excluded_dirs: [Examples]
    php_cpd:
        enabled: true
        excluded_dirs: [Examples]    
