
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm
  
script:
  - echo 'Iriven PHP Session Library'
  
before_install:
  - travis_retry composer self-update

install:
  - composer install

after_success:
 - bash <(curl -s https://codecov.io/bash)
